name: hello_word
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  image_picker: ^1.1.2

  # material_design_icons_flutter: ^7.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  fonts: 
    - family: New Amsterdam
      fonts:
        - asset: fonts/NewAmsterdam-Regular.ttf
          # style: italic
          # wight: 400


